/**
 * TIPID — Monthly Summary Report
 * A shareable receipt-style summary card showing monthly totals,
 * top categories, and budget status.
 */
import { useState, useMemo, useRef } from "react";
import { useTipidStore, formatCurrency } from "@/lib/store";
import CategoryIcon from "@/components/CategoryIcon";
import { motion } from "framer-motion";
import {
  ChevronLeft,
  ChevronRight,
  Download,
  TrendingUp,
  TrendingDown,
  Target,
  ArrowLeft,
} from "lucide-react";
import { useLanguage } from "@/lib/i18n";
import { Link } from "wouter";
import {
  format,
  startOfMonth,
  endOfMonth,
  addMonths,
  subMonths,
} from "date-fns";

export default function MonthlySummary() {
  const { transactions, categories, budgets, settings } = useTipidStore();
  const { lang } = useLanguage();
  const [currentDate, setCurrentDate] = useState(new Date());
  const receiptRef = useRef<HTMLDivElement>(null);

  const monthStart = startOfMonth(currentDate);
  const monthEnd = endOfMonth(currentDate);

  const monthTransactions = useMemo(
    () =>
      transactions.filter((t) => {
        const d = new Date(t.date);
        return d >= monthStart && d <= monthEnd;
      }),
    [transactions, monthStart, monthEnd]
  );

  const totalIncome = monthTransactions
    .filter((t) => t.type === "income")
    .reduce((s, t) => s + t.amount, 0);
  const totalExpense = monthTransactions
    .filter((t) => t.type === "expense")
    .reduce((s, t) => s + t.amount, 0);
  const netBalance = totalIncome - totalExpense;
  const totalTransactions = monthTransactions.length;

  // Top expense categories
  const categoryBreakdown = useMemo(() => {
    const map = new Map<string, number>();
    monthTransactions
      .filter((t) => t.type === "expense")
      .forEach((t) => {
        map.set(t.categoryId, (map.get(t.categoryId) || 0) + t.amount);
      });
    return Array.from(map.entries())
      .map(([catId, amount]) => ({
        category: categories.find((c) => c.id === catId),
        amount,
        percentage: totalExpense > 0 ? (amount / totalExpense) * 100 : 0,
      }))
      .sort((a, b) => b.amount - a.amount)
      .slice(0, 5);
  }, [monthTransactions, categories, totalExpense]);

  // Budget status
  const budgetStatus = useMemo(() => {
    return budgets.map((budget) => {
      const spent = monthTransactions
        .filter(
          (t) => t.type === "expense" && t.categoryId === budget.categoryId
        )
        .reduce((s, t) => s + t.amount, 0);
      const cat = categories.find((c) => c.id === budget.categoryId);
      const percentage = budget.limit > 0 ? (spent / budget.limit) * 100 : 0;
      return { budget, category: cat, spent, percentage };
    });
  }, [budgets, monthTransactions, categories]);

  // Daily average
  const daysInMonth = monthEnd.getDate();
  const daysPassed = Math.min(
    new Date().getDate(),
    daysInMonth
  );
  const dailyAvgExpense =
    daysPassed > 0 ? totalExpense / daysPassed : 0;

  const handleExportText = () => {
    const lines = [
      `═══════════════════════════`,
      `       TIPID MONTHLY REPORT`,
      `═══════════════════════════`,
      ``,
      `  ${format(currentDate, "MMMM yyyy")}`,
      ``,
      `───────────────────────────`,
      `  ${lang === "fil" ? "Kita" : "Income"}:     ${formatCurrency(totalIncome, settings.currency)}`,
      `  ${lang === "fil" ? "Gastos" : "Expenses"}:  ${formatCurrency(totalExpense, settings.currency)}`,
      `───────────────────────────`,
      `  ${lang === "fil" ? "Net" : "Net"}:        ${formatCurrency(netBalance, settings.currency)}`,
      `═══════════════════════════`,
      ``,
      `  ${lang === "fil" ? "Mga Top na Gastos" : "Top Expenses"}:`,
    ];

    categoryBreakdown.forEach((item, i) => {
      lines.push(
        `  ${i + 1}. ${item.category?.name || "Unknown"} — ${formatCurrency(item.amount, settings.currency)} (${item.percentage.toFixed(0)}%)`
      );
    });

    if (budgetStatus.length > 0) {
      lines.push(``);
      lines.push(`  ${lang === "fil" ? "Status ng Budget" : "Budget Status"}:`);
      budgetStatus.forEach((bs) => {
        const status =
          bs.percentage >= 100
            ? "⚠️ OVER"
            : bs.percentage >= 80
            ? "⚡ WARNING"
            : "✅ OK";
        lines.push(
          `  ${bs.category?.name}: ${formatCurrency(bs.spent, settings.currency)}/${formatCurrency(bs.budget.limit, settings.currency)} ${status}`
        );
      });
    }

    lines.push(``);
    lines.push(`───────────────────────────`);
    lines.push(`  ${totalTransactions} ${lang === "fil" ? "na transactions" : "transactions"}`);
    lines.push(`  ${lang === "fil" ? "Avg/araw" : "Avg/day"}: ${formatCurrency(dailyAvgExpense, settings.currency)}`);
    lines.push(`───────────────────────────`);
    lines.push(`  Generated by Tipid`);
    lines.push(`  ${new Date().toLocaleDateString()}`);
    lines.push(`═══════════════════════════`);

    const text = lines.join("\n");
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `tipid-summary-${format(currentDate, "yyyy-MM")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="px-5 pt-6 pb-4">
      {/* Header */}
      <div className="flex items-center gap-3 mb-5">
        <Link href="/app">
          <div className="p-2 rounded-xl hover:bg-accent">
            <ArrowLeft className="w-5 h-5" />
          </div>
        </Link>
        <div>
          <h1 className="text-xl font-extrabold font-display">
            {lang === "fil" ? "Buod ng Buwan" : "Monthly Summary"}
          </h1>
          <p className="text-xs text-muted-foreground font-body">
            {lang === "fil"
              ? "I-share o i-screenshot ang report"
              : "Share or screenshot this report"}
          </p>
        </div>
      </div>

      {/* Month Navigator */}
      <div className="flex items-center justify-between mb-5">
        <button
          onClick={() => setCurrentDate(subMonths(currentDate, 1))}
          className="p-2 rounded-lg hover:bg-accent active:scale-95"
        >
          <ChevronLeft className="w-5 h-5" />
        </button>
        <h2 className="text-base font-bold font-display">
          {format(currentDate, "MMMM yyyy")}
        </h2>
        <button
          onClick={() => setCurrentDate(addMonths(currentDate, 1))}
          className="p-2 rounded-lg hover:bg-accent active:scale-95"
        >
          <ChevronRight className="w-5 h-5" />
        </button>
      </div>

      {/* Receipt Card */}
      <motion.div
        ref={receiptRef}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-card rounded-2xl border border-border/50 overflow-hidden"
      >
        {/* Receipt Header */}
        <div className="bg-primary/5 px-5 py-4 text-center border-b border-dashed border-border/50">
          <p className="text-lg font-extrabold font-display">TIPID</p>
          <p className="text-xs text-muted-foreground font-body mt-0.5">
            {lang === "fil" ? "Buod ng Buwan" : "Monthly Summary Report"}
          </p>
          <p className="text-sm font-bold font-display mt-1">
            {format(currentDate, "MMMM yyyy")}
          </p>
        </div>

        {/* Main Totals */}
        <div className="px-5 py-4 space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-emerald-100 dark:bg-emerald-900/30 flex items-center justify-center">
                <TrendingUp className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
              </div>
              <span className="text-sm font-body text-muted-foreground">
                {lang === "fil" ? "Kita" : "Income"}
              </span>
            </div>
            <span className="text-sm font-bold tabular-nums font-body text-emerald-600 dark:text-emerald-400">
              +{formatCurrency(totalIncome, settings.currency)}
            </span>
          </div>

          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-red-100 dark:bg-red-900/30 flex items-center justify-center">
                <TrendingDown className="w-3.5 h-3.5 text-red-600 dark:text-red-400" />
              </div>
              <span className="text-sm font-body text-muted-foreground">
                {lang === "fil" ? "Gastos" : "Expenses"}
              </span>
            </div>
            <span className="text-sm font-bold tabular-nums font-body text-red-600 dark:text-red-400">
              -{formatCurrency(totalExpense, settings.currency)}
            </span>
          </div>

          <div className="border-t border-dashed border-border/50 pt-3">
            <div className="flex items-center justify-between">
              <span className="text-sm font-bold font-body">
                {lang === "fil" ? "Net Balance" : "Net Balance"}
              </span>
              <span
                className={`text-lg font-extrabold tabular-nums font-display ${
                  netBalance >= 0
                    ? "text-emerald-600 dark:text-emerald-400"
                    : "text-red-600 dark:text-red-400"
                }`}
              >
                {formatCurrency(netBalance, settings.currency)}
              </span>
            </div>
          </div>
        </div>

        {/* Divider */}
        <div className="border-t border-dashed border-border/50" />

        {/* Top Spending Categories */}
        {categoryBreakdown.length > 0 && (
          <div className="px-5 py-4">
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground font-body mb-3">
              {lang === "fil" ? "Mga Top na Gastos" : "Top Expenses"}
            </p>
            <div className="space-y-2.5">
              {categoryBreakdown.map((item, i) => (
                <div key={i} className="flex items-center gap-3">
                  <span className="text-xs font-bold font-body text-muted-foreground w-4">
                    {i + 1}
                  </span>
                  <CategoryIcon
                    categoryId={item.category?.id || ""}
                    iconName={item.category?.icon}
                    color={item.category?.color}
                    size="sm"
                  />
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between mb-0.5">
                      <span className="text-xs font-semibold font-body truncate">
                        {item.category?.name || "Unknown"}
                      </span>
                      <span className="text-xs font-bold tabular-nums font-body">
                        {formatCurrency(item.amount, settings.currency)}
                      </span>
                    </div>
                    <div className="w-full h-1.5 bg-accent rounded-full overflow-hidden">
                      <div
                        className="h-full rounded-full transition-all"
                        style={{
                          width: `${Math.min(item.percentage, 100)}%`,
                          backgroundColor: item.category?.color || "#64748b",
                        }}
                      />
                    </div>
                  </div>
                  <span className="text-[10px] text-muted-foreground font-body w-8 text-right">
                    {item.percentage.toFixed(0)}%
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Budget Status */}
        {budgetStatus.length > 0 && (
          <>
            <div className="border-t border-dashed border-border/50" />
            <div className="px-5 py-4">
              <p className="text-[10px] uppercase tracking-wider text-muted-foreground font-body mb-3">
                <Target className="w-3 h-3 inline mr-1" />
                {lang === "fil" ? "Status ng Budget" : "Budget Status"}
              </p>
              <div className="space-y-2">
                {budgetStatus.map((bs) => (
                  <div
                    key={bs.budget.id}
                    className="flex items-center justify-between"
                  >
                    <div className="flex items-center gap-2">
                      <CategoryIcon
                        categoryId={bs.category?.id || ""}
                        iconName={bs.category?.icon}
                        color={bs.category?.color}
                        size="xs"
                      />
                      <span className="text-xs font-body">
                        {bs.category?.name}
                      </span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-xs tabular-nums font-body">
                        {formatCurrency(bs.spent, settings.currency)}/
                        {formatCurrency(bs.budget.limit, settings.currency)}
                      </span>
                      <span
                        className={`text-[10px] font-bold px-1.5 py-0.5 rounded-full ${
                          bs.percentage >= 100
                            ? "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400"
                            : bs.percentage >= 80
                            ? "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400"
                            : "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400"
                        }`}
                      >
                        {bs.percentage >= 100
                          ? "OVER"
                          : bs.percentage >= 80
                          ? `${bs.percentage.toFixed(0)}%`
                          : "OK"}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </>
        )}

        {/* Footer Stats */}
        <div className="border-t border-dashed border-border/50" />
        <div className="px-5 py-4">
          <div className="flex justify-between text-xs text-muted-foreground font-body">
            <span>
              {totalTransactions}{" "}
              {lang === "fil" ? "na transactions" : "transactions"}
            </span>
            <span>
              {lang === "fil" ? "Avg/araw" : "Avg/day"}:{" "}
              {formatCurrency(dailyAvgExpense, settings.currency)}
            </span>
          </div>
        </div>

        {/* Receipt Tear */}
        <div className="bg-primary/5 px-5 py-3 text-center border-t border-dashed border-border/50">
          <p className="text-[10px] text-muted-foreground font-body">
            Generated by Tipid &bull; {new Date().toLocaleDateString()}
          </p>
        </div>
      </motion.div>

      {/* Export Button */}
      <button
        onClick={handleExportText}
        className="w-full mt-4 py-3 rounded-xl bg-primary text-primary-foreground font-bold font-body text-sm flex items-center justify-center gap-2 hover:opacity-90 transition-opacity active:scale-[0.98]"
      >
        <Download className="w-4 h-4" />
        {lang === "fil" ? "I-export ang Report" : "Export Report"}
      </button>
    </div>
  );
}
